# Generated by Django 2.0.4 on 2018-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle_lunch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='can_go',
            field=models.BooleanField(default=True),
        ),
    ]
